### ISSUE TITLE
Linux sleep kernel parameters

### ISSUE THREAD

**Issue by sos-michael** [olm3ca/Galaxy-Chromebook#1]
Hi Fellow Kohaku Owner! 

So it looks  MrCBx's firmware v4.13 defaults the mem-sleep/suspend state is sleep-2-idle, which really isn't suspend at all! Passing the kernel parameter : "mem_sleep_default=deep" will get you sleeping correctly!

Also, seeing as you are using Manjaro this might not apply, but on Fedora 34, I had to blacklist "elants_i2c". It was hanging sleep.

Hope that helps you and other users who find your guide useful.

**Comment by olm3ca** [comment]
Wow, that is tremendously helpful. Thank you! I'll add that to the Readme... On Fedora 34, you have SOF working? I might need to try that.

I have to send mine in for repairs as the touchpad is completely broken. Hope I get it back quickly so I can keep at this project!

**Comment by sos-michael** [comment]
Sadly SOF works no better on Fedora than it does on Manjaro, but I will admit I didn't give it a lot of effort. I just installed the v1.7 firmware and it worked with whatever version was packaged with fedora. Sadly no headphone jack.

**Comment by olm3ca** [comment]
Got it. Still might give Fedora a go. If you feel like cracking the graphics acceleration mystery in Catalina feel free :-)

**Comment by olm3ca** [comment]
Hey, after a bit of a break, I switched back to Manjaro and tried Windows 11. Incremental progress in both - brightness is working well in W11, and Manjaro seems to be handling audio a little bit better. Are you still using Fedora? Any other findings?
