### ISSUE TITLE
new intel smart sound driver; any update on trackpad support?

### ISSUE THREAD

**Issue by fei8wen** [olm3ca/Galaxy-Chromebook#2]
Hi:
I notice intel has a new driver for their smart sound technology:
https://downloadcenter.intel.com/download/30444/Intel-Smart-Sound-Technology-Intel-SST-Driver-for-Intel-NUC-11-Compute-Element
can you try that out?

Also is there any update on solving sleep/trackpad support on windows?
Thanks

**Comment by olm3ca** [comment]
Hey, apologies for the very late response. I had taken a break on this, but just set up Windows 11 on this device. Screen brightness now works correctly, but the touchpad and sound are still not working. Thanks for that link - tried it, and no change. You can use the pen with the screen, but it's obviously not ideal to loose this much functionality. For now, Manjaro still seems to provide the best hardware support. Thanks!

**Comment by olm3ca** [comment]
Hi @fw-tamu - driver support is now available for the touchpad and touchscreen in Windows, I thought you'd like to know.

**Comment by fei8wen** [comment]
> Hi @fw-tamu - driver support is now available for the touchpad and touchscreen in Windows, I thought you'd like to know.

Glad to know that it works now! However I already returned it.
