### ISSUE TITLE
Getting audio to work properly

### ISSUE THREAD

**Issue by mingming1222** [olm3ca/Galaxy-Chromebook#4]
Hi, @olm3ca  @CabbageSong  I modified the original alsa ucm config for chrome os and now the sof is displayed and works fine with the new HiFi.conf. Just need to
Move this repository https://github.com/mingming1222/galaxy-chromebook-linux folder sof-cmlda7219ma to /usr/share/alsa/ucm2 directory.

Since I don't have a monitor at home, I didn't test the hdmi port, so I commented this part out. But I believe hdmi should work fine too.

**Comment by olm3ca** [comment]
This is great, thank you!

**Comment by CabbageSong** [comment]
@mingming1222 Great! The sound and mic work, but actually I don't figure out how the magic code does with sof.

**Comment by nullterminated** [comment]
I was so happy you fixed this @mingming1222 and it worked great for about 2 weeks. But after a pacman -Syu today, I'm back to broken audio with the default "Stereo Output" and "Pro Audio" profiles. I 'diff sof-cmlda7219ma/ /usr/share/alsa/ucm2/sof-cmlda7219ma/' and there are no changes, so it seems like it's not finding/loading the conf now.

**Comment by mingming1222** [comment]
@nullterminated  Hi, alsa-lib was recently upgraded to v1.2.6.1, this version modified the configuration directory of ucm, you need to migrate the sof-cmlda7219ma configuration file to /usr/share/alsa/ucm2/conf.d/ . it works in fedora, archlinux should also work

**Comment by nullterminated** [comment]
@mingming1222 that worked beautifully! Thank you for the tip.

**Comment by nullterminated** [comment]
Once again, an update appears to have moved where the conf files need to be located. I'm looking for the fix on my own, but any tips are certainly appreciated.

edit: If I downgrade to alsa-lib 1.2.6.1 the config is found again.

**Comment by heywoodlh** [comment]
For those of us who can't downgrade alsa-lib (on Arch, don't have the old version in my cache), what is the proper fix? Because placing the files in `/usr/share/alsa/ucm2/conf.d/` does not work anymore.

**Comment by nullterminated** [comment]
@heywoodlh If/when I find a solution, I'll be sure to share it. In the meantime, you can find the downgrade here,

https://archive.archlinux.org/packages/a/alsa-lib/

Download it, verify sig, pacman -U the zst.

**Comment by nullterminated** [comment]
Looks related,

https://github.com/alsa-project/alsa-ucm-conf/issues/168

**Comment by nullterminated** [comment]
The problem seems resolved now. I updated to extra/alsa-lib 1.2.7.2-1 and the config is no longer broken. Yay!

**Comment by olm3ca** [comment]
Excellent, thanks @nullterminated for following up!
