### ISSUE TITLE
Kernel 5.15+ hangs on reboot, shutdown, and sleep

### ISSUE THREAD

**Issue by nullterminated** [olm3ca/Galaxy-Chromebook#6]
Just a heads up for distros that are not using a bleeding edge kernel. I've been running Arch Linux on this chromebook. Since the 5.15 kernel, sleep will hard lock the system (keyboard/mouse/clock on menubar/etc are not responsive, have to hold down power key and force a reboot). Reboot and shutdown hang at the final stage (unloading KVM). Blacklisting KVM didn't work, it just hangs at the next step up. 5.14 worked. The problem started with 5.15. v5.10.90 lts works fine as well, and this seems to be the last lts package from arch that works properly.

**Comment by olm3ca** [comment]
Very good to note, thank you for posting this.

**Comment by sos-michael** [comment]
I'm on F35 with the 5.16 rawhide-nodebug kernel and am not experiencing any sleep related issue. Maybe some more logging info might help? I didn't intentionally turn it off, but maybe i have hardware virtualization off? Searching my logs for KVM doesn't return any hits.

**Comment by nullterminated** [comment]
@sos-michael Good to know it works for someone. Perhaps I should look for any changes in the kernel build/config for 5.15 on arch. I booted into 5.16, sleep by closing the lid, and then after freeze and reboot, did a journalctl -b-1. I don't see any errors between

systemd-logind[826]: Lid closed.

and

systemd-sleep[1535]: Entering sleep state 'suspend'...

And that's the end of the log, there's nothing else indicating why it fails to wake. When I reopen the lid, all I see is black screen with mouse cursor. Nothing is changed except the kernel. Same kernel options and all. 

Out of curiosity, what kernel options are you booting with?

On the 5.10.x kernel where I can sleep and wake successfully, the next line I see in journalctl after the above systemd-sleep line is,

kernel: PM: suspend entry (deep)

It seems like something happening between those two points in logging kills it.

**Comment by brpjerry** [comment]
Running Arch Linux, kernel 5.16.16-arch1-1. I had this problem as well, but blacklisting the cros_ec_typec kernel module fixed the issue. Now suspend/reboot both work fine.

**Comment by nullterminated** [comment]
That did the trick for me too. I was beginning to wonder how long I could ignore kernel updates and stay on 5.10.92. Thanks a bunch for the tip, now I'm back to latest mainline. Perhaps this note can be added to the readme? 

FWIW, on my machine I have,

```
$ cat /etc/modprobe.d/blacklist.conf 
blacklist atmel_mxt_ts
blacklist cros_ec_typec
```

First line for the touchscreen fix, second for this.

**Comment by olm3ca** [comment]
Thanks to both of you - I've added this to the readme.

**Comment by nullterminated** [comment]
Thanks again everyone. Looks like this is solved.
