### ISSUE TITLE
Windows Driver from SGC2?

### ISSUE THREAD

**Issue by sos-michael** [olm3ca/Galaxy-Chromebook#7]
I'm not a windows but found this trolling github...

https://github.com/ljhholer/Samsung-Galaxy-Book-2-Hardware-Drivers/releases/tag/main

Maybe there is some overlap... especially with the sound driver?

**Comment by olm3ca** [comment]
That's a very nice find. Thank you - I hope someone can test, I no longer own this device. It's tempting though!

**Comment by olm3ca** [comment]
Actually these are for the Galaxy Book, which is an ARM device. Useful for another machine but not this one. Thanks anyway though!
