### ISSUE TITLE
Drivers for windows

### ISSUE THREAD

**Issue by amir1373** [olm3ca/Galaxy-Chromebook#8]
Hi 
what has been done on this device is really great and makes this device capable of much more than what chrome os alone can achieve. I for one am really grateful for the job community has done here and I was wondering if there is any chance the rest of the drivers are also ready for windows?
thanks again

**Comment by olm3ca** [comment]
I don't have any information on that, but I do know from several developers on Discord that the drivers may never be released. I hope otherwise. Closing this as there are no updates, thanks
