### ISSUE TITLE
Installing windows 10/11

### ISSUE THREAD

**Issue by MaCleodWalker** [olm3ca/Galaxy-Chromebook#9]
When installing windows with a USB I get a blue screen error acpi bios errors

**Comment by olm3ca** [comment]
That never happened to me. Maybe something changed in MrChromebox's script, or maybe your Windows install media is bad. Try again with a new Windows 10 or 11 install USB.

**Comment by MaCleodWalker** [comment]
I've tried both 10 and 11 with different USB drives but all I get is the same error I've also tried a windows to go USB drive but still the same error, another user([sky-ranch](https://github.com/sky-ranch))  is having the same issue today and has started a a subreddit for the issue (https://www.reddit.com/r/chrultrabook/comments/vs0xpv/acpi_bios_error_on_galaxy_chrome_book_kohaku/)

**Comment by olm3ca** [comment]
It looks like MrChromebox is aware of this issue, and a new firmware version will be pushed out soon. I don't think I can help with this but hope it's resolved for you soon.
